version: "3.9"

services:
  mysql:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    command: bash /wp-dev/scripts/wordpress-command.sh
    volumes:
      - wp_data:/var/www/html
      - ./scripts:/wp-dev/scripts
      - ./plugins:/wp-dev/plugins
      - ./themes:/wp-dev/themes
      - ./config:/wp-dev/config
    ports:
      - 8080:8080
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  wordpress-cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    entrypoint: cp /usr/local/bin/wp /var/www/html/
    user: xfs
    volumes:
      - wp_data:/var/www/html
      - ./scripts:/wp-dev/scripts

volumes:
  db_data: {}
  wp_data: {}
