version: "3.9"

networks:
  local: {}

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - local
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - local
    ports:
      - 8081:80

  wordpress:
    image: wordpress:latest
    command: bash /wp-dev/scripts/wordpress-command.sh
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - local
    ports:
      - 8080:80
    restart: on-failure
    volumes:
      - www:/var/www/html
      - ./scripts:/wp-dev/scripts
      - ./plugins:/wp-dev/plugins
      - ./themes:/wp-dev/themes

  wordpress-cli:
    image: wordpress:cli
    depends_on:
      - mysql
      - wordpress
    entrypoint: cp /usr/local/bin/wp /var/www/html/
    networks:
      - local
    user: xfs
    volumes:
      - www:/var/www/html
      - ./scripts:/wp-dev/scripts

volumes:
  database: {}
  www: {}
